CREATE TABLE `ATTRIBUTION_MODEL_2` (
  `OID` bigint(20) NOT NULL,
  `VERSION` bigint(20) NOT NULL DEFAULT '0',
  `NAME` varchar(50) NOT NULL,
  PRIMARY KEY (`OID`),
  UNIQUE KEY `UC_ATTRIBUTION_MODEL_NAME_2` (`NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
